#+TITLE: The Lowball
#+KEYWORDS: The Lowball, Lowball, Politics, Diplomacy, Military
#+LANGUAGE: English
#+DESCRIPTION: The Lowball, a political game that combines elements of chance and strategy.
#+HTML_HEAD: <meta name="google-site-verification" content="V04ybF9ZI7TE9SR7Z0nXWf0h-HAVPGhlRfefUice9rw" /> <!-- Global site tag (gtag.js) - Google Analytics --> <script async src="https://www.googletagmanager.com/gtag/js?id=G-6D0151J5EX"></script> <script>   window.dataLayer = window.dataLayer || [];  function gtag(){dataLayer.push(arguments);}  gtag('js', new Date());  gtag('config', 'G-6D0151J5EX');</script>


* The Lowball
** Definition
   - A Political Game that combines elements of Chance and Strategy.
** Players
   - Participants in the Game.
#+BEGIN_SRC
 * Space
  * Earth, Universes
 * Space
  * Humans, Souls, Zodiacs
 * Space
  * Sovereign Entities
#+END_SRC
** Decks
#+BEGIN_SRC
   - A Deck fits with an ordered list of labels of Players.
     * Labels are symbols of the Players (Flag, Coat of Arms, Logo, et cetera).
   - A Deck can be of different types:
     * Sovereign Entities
     * Non-State Actors
     * Companies
     * Foundations
     * Sub-State Actors
       - Agencies
       - Militaries
       - Departments
       - Legislative
     * Individuals
#+END_SRC
** The Lowball
#+BEGIN_SRC
The Lowball
 * Epoch                                                                :card:
 * [[The Dot/The Dot.html][The Dot]]                                                              :card:
 * The Table                                                            :card:
 * Pangaea                                                              :card:
 * Pigments                                                             :card:
 * Chance in the House of Fate                                          :card:
 * Color Scales                                                         :card:
 * A New Geometry                                                       :card:
 * Intervals                                                            :card:
 * Positional Spots                                                     :card:
 * Battle of the First Defense Forward
 * Players
#+END_SRC
** Acknowledgement
  * United States of America
  * United Kingdom of Great Britain and Northern Ireland
  * Russian Federation
  * People's Republic of China
  * Kingdom of Saudi Arabia
  * Islamic Republic of Iran
  * Vatican City State
  * New Zealand
  * French Republic
  * Japan
  * Republic of India
  * State of Kuwait
  * Kingdom of Sweden
  * Federal Republic of Germany
  * Republic of Korea
  * Canada
  * Commonwealth of Australia

* Keywords
Politics, Diplomacy, Military, The Lowball.

* Author

*Jad Saklawi* [[mailto:jad.saklawi@gmail.com][<jad.saklawi@gmail.com]]>

 * Twitter: [[https://twitter.com/jadsaklawi][@jadsaklawi]]
 * [[https://www.instagram.com/jadsaklawi_/][Instagram]]
 * [[https://github.com/jadsaklawi][GitHub]]
